### ISSUE TITLE
UnitCompiler fails with CompileException when parent interface method is overridden in child interface with subtype return type

### ISSUE THREAD

**Issue by vvysotskyi** [janino-compiler/janino#47]
Hi,
Apache Calcite uses Janino 2.7.6 for compiling code which is used for handling different kinds of query metadata. All was working fine before bumping up Java version in maven-compiler-plugin to 1.8. After this, some tests failed with compile exceptions for generated code. The same issue is observed with Janino 3.0.7.

I have reproduced it on the current Janino master. 
When Java version 1.8 is specified in `janino-parent/pom.xml` `maven-compiler-plugin` for both `source` and `target`, the next test placed into `CompilerTest.java` is failed:
```
    public interface A {
        A theFirstMethod();
    }

    public interface B extends A {
        B theFirstMethod();
        Object theSecondMethod();
    }

    @Test
    public void testInterfaceWithOverriddenMethod() throws Exception {
        SimpleCompiler s = new SimpleCompiler();
        s.setDebuggingInformation(true, true, true);
        s.cook("package pkg;\n"
            + "public class D {\n"
            + "    public java.lang.Object one(org.codehaus.janino.tests.CompilerTest.B b) { \n"
            + "       return b.theFirstMethod().theSecondMethod();\n"
            + "    }\n"
            + "}\n");
        s.getClassLoader().loadClass("pkg.D");
    }
```
Error message and stacktrace:
```
org.codehaus.commons.compiler.CompileException: Line 4, Column 50: A method named "theSecondMethod" is not declared in any enclosing class nor any supertype, nor through a static import

	at org.codehaus.janino.UnitCompiler.compileError(UnitCompiler.java:12063)
	at org.codehaus.janino.UnitCompiler.findIMethod(UnitCompiler.java:8955)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5018)
	at org.codehaus.janino.UnitCompiler.access$9100(UnitCompiler.java:215)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4378)
	at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4351)
	at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5051)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4351)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5533)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2649)
	at org.codehaus.janino.UnitCompiler.access$2800(UnitCompiler.java:215)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1504)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1487)
	at org.codehaus.janino.Java$ReturnStatement.accept(Java.java:3541)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1487)
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1567)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3356)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1357)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1330)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:822)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:432)
	at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:215)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:411)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:406)
	at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1406)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:406)
	at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:378)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:237)
	at org.codehaus.janino.SimpleCompiler.compileToClassLoader(SimpleCompiler.java:465)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:216)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:207)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:80)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:75)
	at org.codehaus.janino.tests.CompilerTest.testInterfaceWithOverriddenMethod(CompilerTest.java:440)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
It looks like the overridden method `A theFirstMethod()` from the parent interface `A` was chosen instead of the method from interface `B` when `b.theFirstMethod()` was executed.

Also, I have noticed that with Java 8 the next code:
```
        Method[] declaredMethods = Class.forName("org.codehaus.janino.tests.CompilerTest$B").getDeclaredMethods();
        for (Method m : declaredMethods) {
            System.out.println(m);
        }
```
returns
```
public abstract org.codehaus.janino.tests.CompilerTest$B org.codehaus.janino.tests.CompilerTest$B.theFirstMethod()
public default org.codehaus.janino.tests.CompilerTest$A org.codehaus.janino.tests.CompilerTest$B.theFirstMethod()
public abstract java.lang.Object org.codehaus.janino.tests.CompilerTest$B.theSecondMethod()
```
So perhaps in our case that `default` method was chosen instead of the correct one.

**Comment by julianhyde** [comment]
Here is the corresponding Calcite case: https://issues.apache.org/jira/browse/CALCITE-2259

**Comment by aunkrig** [comment]
Java 7 changed in JLS 1.12.2.5.BL2.B1.BL.B2 the sentence

> The most specific method is chosen arbitrarily among the maximally specific methods.

to

> the most specific method is chosen arbitrarily among the subset of the maximally specific methods that have the most specific return type.

to accomodate for "covariant return types". JANINO does not honor this change, so the result is random.

Cannot add a test case for this to ```ReportedIssuesTest``` because that is compiled with JAVAC 6 and not JAVAC 7, so there will be no regression testing for this bug. Bummer.

Fixed the bug; please test!

> commit -m "GITHUB issue #47: UnitCompiler fails with CompileException when parent interface method is overridden in child interface with subtype return type" -N C:/workspaces/janino/janino/src/main/java/org/codehaus/janino/UnitCompiler.java
>     Sending        C:/workspaces/janino/janino/src/main/java/org/codehaus/janino/UnitCompiler.java
>     Transmitting file data ...
>     Committed revision 1464.
>

**Comment by aunkrig** [comment]
> UnitCompiler.findMostSpecificIInvocable() method at the end chooses non-abstract methods (9328 line), so at this stage, since the interface was used, all methods were the abstract ones except the default method, so it was added into maximallySpecificIInvocables list.

I don't quite get it... what is a "default method"?
Anyway, here is the test case that I used to reproduce the problem:

```
package issue47;

import static org.junit.Assert.*;

import org.codehaus.janino.SimpleCompiler;
import org.junit.Test;

public class Issue47 {

    public interface A {
        A theFirstMethod();
    }

    public interface B extends A {
        B theFirstMethod();
        Object theSecondMethod();
    }

    @Test
    public void testInterfaceWithOverriddenMethod() throws Exception {
        
        SimpleCompiler s = new SimpleCompiler();
        s.setDebuggingInformation(true, true, true);
        
        // Throws "CompileException: Line 4, Column 50: A method named "theSecondMethod" is not declared in any
        // enclosing class nor any supertype, nor through a static import" iff interfaces A and B are _compiled_
        // with JAVAC 8.
        s.cook(
            ""
            + "package pkg;\n"
            + "public class D {\n"
            + "    public java.lang.Object one(issue47.Issue47.B b) { \n"
            + "       return b.theFirstMethod().theSecondMethod();\n"
            + "    }\n"
            + "}\n"
        );
        s.getClassLoader().loadClass("pkg.D");
    }}
```

Can you please try that in your environment and report the compile errors?

**Comment by vvysotskyi** [comment]
Besides the test, to reproduce this issue should be set Java version 1.8 in `maven-compiler-plugin` for `source` and `target`. With 1.8 it is reproduced with the same compile error as in the first comment.

Saying "default method" I meant Java 8 feature, a method in the interface with implementation. It is not clear, why it has appeared in the list of methods of the interface `B` (it was mentioned in the first comment).

**Comment by srowen** [comment]
This _might_ be related to https://issues.apache.org/jira/browse/SPARK-25029 . In the build for Scala 2.12, we're encountering errors like this from Janino when compiling generated code:

```
Caused by: org.codehaus.janino.InternalCompilerException: Two non-abstract methods "public int scala.collection.TraversableOnce.size()" have the same parameter types, declaring type and return type
at org.codehaus.janino.UnitCompiler.findMostSpecificIInvocable(UnitCompiler.java:9112)
at org.codehaus.janino.UnitCompiler.findMostSpecificIInvocable(UnitCompiler.java:8888)
at org.codehaus.janino.UnitCompiler.findIMethod(UnitCompiler.java:8770)
at org.codehaus.janino.UnitCompiler.findIMethod(UnitCompiler.java:8672)
at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:4737)
```

It seems clearly to have been triggered by a difference in Scala 2.12, either compiler or collections API, as everything works fine on Scala 2.11. And of course Scala 2.12 changed to use the Java 8 mechanisms -- default methods, lambda metafactory -- when it generates code.

I do wonder whether the fact that it seems to be complaining about finding multiple definitions of `TraversableOnce.size()` in this case could relate to those implementations working differently in the bytecode for trait `TraversableOnce`, relating to default methods? Ref: https://www.scala-lang.org/news/2.12.0/#traits-compile-to-interfaces

**Comment by adriaanm** [comment]
This sounds like it's related to this spec diff from 7 to 8 in https://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.12.2.2

```diff
If exactly one of the maximally specific methods is 
- not declared abstract,
+ concrete (that is, non-abstract or default),
it is the most specific method.

Otherwise, if all the maximally specific methods are 
- declared abstract,
+ abstract or default,
and the signatures of all of the maximally specific methods have the same erasure (§4.6), 
then the most specific method is chosen arbitrarily among the subset of the maximally 
specific methods that have the most specific return type.

+ In this case, the most specific method is considered to be abstract. 
- However,
+ Also,
the most specific method is considered to throw a checked exception if and only if that exception 
or its erasure is declared in the throws clauses of each of the maximally specific methods.
```

To verify for this specific case:
```scala
$ scala
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> def allSizeMethods(cls: Class[_]): List[java.lang.reflect.Method] = Option(cls.getSuperclass).toList.flatMap(allSizeMethods) ++ cls.getInterfaces.toList.flatMap(allSizeMethods) ++ List(cls.getMethod("size"))
allSizeMethods: (cls: Class[_])List[java.lang.reflect.Method]

scala> allSizeMethods(classOf[scala.collection.TraversableOnce[_]])
res0: List[java.lang.reflect.Method] = List(public abstract int scala.collection.GenTraversableOnce.size(), public default int scala.collection.TraversableOnce.size())
```

Thus, the most specific version is the one in `TraversableOnce`

**Comment by adriaanm** [comment]
(If we upgrade our experiment a bit, you can also see the second delta kicking into action.)

```scala
scala> def allSizeMethods(cls: Class[_]): List[java.lang.reflect.Method] = 
  Option(cls.getSuperclass).toList.flatMap(allSizeMethods) ++
    cls.getInterfaces.toList.flatMap(allSizeMethods) ++ 
    util.Try(cls.getMethod("size")).toOption.toList
allSizeMethods: (cls: Class[_])List[java.lang.reflect.Method]

scala> allSizeMethods(classOf[scala.collection.immutable.Seq[_]]).distinct.foreach(println)
public abstract int scala.collection.GenTraversableOnce.size()
public default int scala.collection.TraversableOnce.size()
public abstract int scala.collection.GenTraversableLike.size()
public default int scala.collection.SeqLike.size()
```

**Comment by srowen** [comment]
@adriaanm what do you think of https://github.com/janino-compiler/janino/pull/54 ?

**Comment by aunkrig** [comment]
We have kind of a mess in this issue; let's get back to the original problem.

I added a test case that should reproduce the problem, but it succeeds in all combinations of janino/jdk and jre6/7/8.

> commit -m "Added a test case for issue 47." -N C:/dev/EclipseWS/janino/commons-compiler-tests/src/test/java/org/codehaus/commons/compiler/tests/ReportedBugsTest.java
>     Committed revision 1479.

Please verify that there *is* a problem here, otherwise I'd close this issue.

**Comment by vvysotskyi** [comment]
@aunkrig, this test will fail when set 1.8 jdk version for `maven-compiler-plugin` in the `pom.xml` file.

**Comment by adriaanm** [comment]
Perhaps there is more than one problem here, but the one I was commenting on is that you're reporting an error that's not warranted by JLS8, because it allows multiple default methods (i.e. non-abstract but defined in an interface) with the same erased signature. This is hinted at by the spec diff in my comment above -- see the second chunk.

**Comment by srowen** [comment]
@aunkrig thank you and apologies if I have made a mess here; there are a couple threads here but possibly one common cause. 

The proposed change at https://github.com/janino-compiler/janino/pull/54 might be less noisy to evaluate, which follows @adriaanm 's lead about the spec difference that might need to be taken into account.

Yes, this is surely specific to Java 8 and later, and may manifest most easily in Scala 2.12+ apps, which are going to make heavy use of Java 8's provision for method definitions in interfaces. https://issues.apache.org/jira/browse/SPARK-25029 is kind of an existence proof of the issue as it triggers the internal error.

**Comment by aunkrig** [comment]
Please test whether version 3.0.9 fixes the problem.

**Comment by vvysotskyi** [comment]
Thanks, it fixes the problem for Calcite project also!

**Comment by aunkrig** [comment]
Great news!
I added a reference from the JANINO home page to the CALCITE home page.

**Comment by julianhyde** [comment]
Thanks for referencing Apache Calcite. We are big fans. (Thanks again for your work, @aunkrig!)

Can you please remove "Optiq" from the list. It is the predecessor of Calcite and is obsolete.

**Comment by aunkrig** [comment]
Thanks for the hint; done.
