### ISSUE TITLE
security documentation not up to date?

### ISSUE THREAD

**Issue by eric-therond-sonarsource** [janino-compiler/janino#127]
Hello,
the security documentation:
* http://janino-compiler.github.io/janino/#security

mention that we can set permissions when evaluating script:
```
ScriptEvaluator se = new ScriptEvaluator();
Permissions permissions = new Permissions();
permissions.add(new PropertyPermission("foo", "read"));
se.setPermissions(permissions);
```
it is working well with version 3.0.7 of janino:
```
<dependency>
    <groupId>org.codehaus.janino</groupId>
    <artifactId>janino</artifactId>
    <version>3.0.7</version>
</dependency>
```
but not with the latest janino version:
```
<dependency>
    <groupId>org.codehaus.janino</groupId>
    <artifactId>janino</artifactId>
    <version>3.1.2</version>
</dependency>
```
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project test: Compilation failure
[ERROR] test.java:[44,9] cannot find symbol
[ERROR]   symbol:   method setPermissions(java.security.Permissions)
[ERROR]   location: variable se of type org.codehaus.janino.ScriptEvaluator

```

Eric

**Comment by aunkrig** [comment]
Sorry for the late answer...

```ISimpleCompiler.setPermissions()``` was marked as DEPRECATED on 2019-12-11 (but that was never released as a version), and then replaced with the new ```org.codehaus.commons.compiler.Sandbox``` class (released as version 3.1.1).

Unfortunately I missed to describe that important (incompatible) change in the change log and the documentation on the project homepage. I did that now, and you should be able to use the new (still very simple) API in your projects.

Please review and comment!
